### ISSUE TITLE
Soul Sand Valley lack advancements

### ISSUE THREAD

**Issue by Frozeh** [Mine-Treasure/Mine-Treasure-Website#1]
![image](https://user-images.githubusercontent.com/59451552/212742972-d06a41c8-5099-48bd-819e-9133b41386ea.png)

Might be a change in Mine Treasure itself.

**Comment by supercrafter100** [comment]
Fixed in [755f4df](https://github.com/Mine-Treasure/Mine-Treasure-Website/commit/755f4df8e060a376f6106a9a6929d2ebeadc5ee9)
