### ISSUE TITLE
Deep Dark lack advancements

### ISSUE THREAD

**Issue by Frozeh** [Mine-Treasure/Mine-Treasure-Website#2]
![image](https://user-images.githubusercontent.com/59451552/212743192-350e1746-4bd4-4ace-b31c-f8b585efdbcf.png)

Might be a change in the new MT update.

**Comment by supercrafter100** [comment]
Fixed in [755f4df](https://github.com/Mine-Treasure/Mine-Treasure-Website/commit/755f4df8e060a376f6106a9a6929d2ebeadc5ee9)
